- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
    - url: https://github.com/SirTarragon/PythonChess

- name: C Sharp
  logo: csharp
  url: https://dotnet.microsoft.com/en-us/languages/csharp/
  color: '#9B4F97'
  projects:
    - url: https://github.com/fsu-fall2022-capstone/Project-Group-4
    - url: https://github.com/SirTarragon/Tasker
